---
- name: Settings for beast server
  hosts: all

  tasks:
  - name: package installation
    yum:
      name:
        - docker
        - docker-python
        - qemu-kvm
        - libvirt
        - virt-install
        - cockpit-machines
        - cockpit-packagekit
        - cockpit-shell
        - cockpit-storaged
        - cockpit-system
        - cockpit-pcp
        - cockpit-ws
        - subscription-manager-cockpit
        - cockpit-docker
      state: latest

  - name: services
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - docker
      - cockpit.socket
      - libvirtd

  - name: firewall rules
    firewalld:
      service: "{{ item }}"
      state: enabled
      immediate: yes
      permanent: yes
    with_items:
      - cockpit
      #- libvirt
      #- libvirt-tls
 
...
