---
- name: Settings for beast server
  hosts: all

  tasks:
  - name: variables
    include_vars: subscription-manager.vault

  - name: set hostname
    hostname:
      name: "beast.pladd.net"

  - name: subscribe system
    redhat_subscription:
      username: "{{ subscription_manager_id }}"
      password: "{{ subscription_manager_pw }}"
      pool_ids: "8a85f9833e1404a9013e3cddf95a0599" # Employee SKU
      # pool_ids: "8a85f9815a1e73d7015a1ea518f82518" # Virt DC
      #pool_ids:
      #  - "8a85f9833e1404a9013e3cddf95a0599"
      #  - "8a85f9815a1e73d7015a1ea518f82518": 2

  - name: repositories
    rhsm_repository:
      name:
        - "rhel-7-server-rpms"
        - "rhel-7-server-optional-rpms"
        - "rhel-7-server-extras-rpms"
        - "rhel-7-server-ansible-2-rpms"
      state: enabled

  - name: System up to date
    yum:
      name:  '*'
      state: latest

  - name: package installation
    yum:
      name:
        - bash-completion
        - pciutils
        - unzip
        - vim
        - wget
        - numactl
        - sos
        - ansible
        - iotop
        - net-tools
        - nmap
        - tcpdump
        - traceroute
        - wireshark
        - bind-utils # for dig
        - rsync
        - git
        - sysstat
      state: latest

...
