---
- name: Settings for beast server
  hosts: all

  tasks:
  - name: rhel7 image pull
    docker_image:
      name: registry.access.redhat.com/rhel7
      state: present

  - name: firewall rules
    firewalld:
      service: "{{ item }}"
      state: enabled
      immediate: yes
      permanent: yes
    with_items:
      - cockpit
      #- libvirt
      #- libvirt-tls
 
...
